# Mitwirken {.unnumbered}

Wir freuen uns über alle, die hier mitwirken, kommentieren, oder Teile schreiben wollen :)


## hilfreiche Quarto Funktionen

(aus der Dokumentation rauskopiert)


:::{.callout-note}
Note that there are five types of callouts, including: 
`note`, `tip`, `warning`, `caution`, and `important`.
:::

::: {.column-margin}
Sidebar text
:::

[This is a span that has the class aside which places it in the margin without a footnote number.]{.aside}

See @knuth84 for additional discussion of literate programming.

Here is an inline note.^[Inlines notes are easier to write,
since you don't have to pick an identifier and move down to
type the note.]


## Footnotes

Here is a footnote reference,[^1] and another.[^longnote]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.

        { some.code }

    The whole paragraph can be indented, or just the first
    line.  In this way, multi-paragraph footnotes work like
    multi-paragraph list items.

This paragraph won't be part of the note, because it
isn't indented.